apiVersion: v1
kind: Service
metadata:
  name: my-lb-service
  labels:
    name: nginx
spec:
  selector:
    name: nginx
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer


