apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app.kubernetes.io/name: nginx
  externalIPs:
  - 10.99.123.205
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
