apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  replicas: 1
  template:
    metadata:
      name: nginx
      labels:
        name: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
  selector:
    matchLabels:
      name: nginx
