apiVersion: v1
kind: Service
metadata:
  name: my-clusterip-service
  namespace: default
spec:
  externalip:
  - 35.234.123.92
  selector:
    name: nginx
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
  type: ClusterIP

