apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx
  name: my-nodeport-service
  namespace: default
spec:
  ports:
  - nodePort: 30940
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    name: nginx
  sessionAffinity: None
  type: NodePort
