apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
spec:
  serviceName: "nginx"
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        env:
         - name: JAVA
           value: "1.9"
        volumeMounts:
          - name: foo
            mountPath: "/etc/foo"
            readOnly: true
          - name: claim-log-1
            mountPath: "/var/log/nginx"
      volumes:
        - name: foo
          configMap:
            name: game-demo
        - name: claim-log-1
          persistentVolumeClaim:
            claimName: claim-log-1

